// Contenido de la web. Todo el texto SEO vive aquí; build.mjs genera el HTML.
// Revisar con el centro: precios, horarios de cada clase, fotos reales y titulaciones.

export const site = {
  name: 'NOVA Centro de Bienestar',
  shortName: 'NOVA',
  url: 'https://novamostoles.com',
  owner: 'Beatriz Manzanero',
  phone: '+34 645 265 946',
  phoneHref: 'tel:+34645265946',
  whatsapp: 'https://wa.me/34645265946',
  street: 'Paseo de Goya 26 (posterior)',
  postalCode: '28932',
  city: 'Móstoles',
  region: 'Madrid',
  country: 'ES',
  hours: 'Lunes a viernes, de 9:30 a 21:30 (con cita previa)',
  mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Paseo+de+Goya+26+28932+M%C3%B3stoles',
  mapsEmbed: 'https://www.google.com/maps?q=Paseo+de+Goya+26,+28932+M%C3%B3stoles,+Madrid&output=embed',
  facebook: '',
  instagram: '',
};

export const categories = [
  {
    slug: 'clases',
    name: 'Clases',
    title: 'Clases de Pilates, Yoga e Hipopresivos en Móstoles | NOVA',
    description: 'Clases en grupos reducidos de Pilates suelo, Yoga, Hipopresivos, Circuito Funcional y Taichí en Móstoles. También sesiones online. Pide tu clase de prueba.',
    h1: 'Clases de movimiento consciente en Móstoles',
    kicker: 'Moverse bien',
    intro: 'Grupos reducidos, atención real a cada alumno y un ambiente tranquilo para trabajar fuerza, movilidad y respiración. Elige la disciplina que mejor encaja contigo o combínalas.',
    color: 'sage',
  },
  {
    slug: 'terapias',
    name: 'Terapias',
    title: 'Masajes y Terapias Manuales en Móstoles | Drenaje, Osteopatía | NOVA',
    description: 'Drenaje linfático, maderoterapia, masaje holístico, osteopatía, reflexología y terapia craneosacral en Móstoles. Sesiones personalizadas con cita previa.',
    h1: 'Terapias manuales y masajes en Móstoles',
    kicker: 'Soltar tensión',
    intro: 'Sesiones individuales en las que escuchamos primero y tratamos después. Técnicas manuales para aliviar tensiones, mejorar la circulación y recuperar la sensación de ligereza.',
    color: 'clay',
  },
  {
    slug: 'estetica',
    name: 'Estética',
    title: 'Estética en Móstoles | Pestañas, Cejas y Spa | NOVA',
    description: 'Lifting de pestañas, microblading de cejas y spa capilar en Móstoles. Resultados naturales en un centro de bienestar tranquilo. Reserva tu cita.',
    h1: 'Estética natural en Móstoles',
    kicker: 'Cuidarse por fuera',
    intro: 'Tratamientos de belleza pensados para realzar lo que ya tienes, con resultados naturales y sin prisas, en el mismo espacio tranquilo donde cuidas tu cuerpo.',
    color: 'gold',
  },
];



export const services = [
  // ───────────── CLASES ─────────────
  {
    slug: 'pilates-mostoles',
    cat: 'clases',
    icon: 'pilates',
    name: 'Pilates suelo',
    title: 'Pilates en Móstoles | Clases en grupos reducidos | NOVA',
    description: 'Clases de Pilates suelo en Móstoles para todos los niveles. Grupos reducidos y corrección personalizada para mejorar postura y espalda.',
    h1: 'Pilates en Móstoles',
    lead: 'Clases de Pilates suelo en grupos reducidos para fortalecer el centro del cuerpo, mejorar la postura y moverte sin dolor.',
    intro: [
      'El método Pilates trabaja la musculatura profunda —abdomen, suelo pélvico y la zona lumbar— a través de ejercicios controlados, conscientes y coordinados con la respiración. Es una forma de entrenar que fortalece sin castigar las articulaciones.',
      'En NOVA impartimos Pilates suelo con material (aros, pelotas, bandas elásticas y foam roller) en grupos pequeños, para que cada alumno reciba correcciones y adaptaciones según su nivel y su historia física.',
    ],
    benefits: [
      'Fortalece el core y protege la espalda',
      'Mejora la postura y la alineación corporal',
      'Aumenta la flexibilidad y la movilidad articular',
      'Ayuda a prevenir y aliviar el dolor lumbar y cervical',
      'Trabaja la respiración y la concentración',
    ],
    forWho: [
      'Personas que empiezan de cero y quieren un ejercicio seguro',
      'Quien pasa muchas horas sentado o tiene molestias de espalda',
      'Deportistas que buscan mejorar su estabilidad y prevenir lesiones',
      'Mujeres en etapa posparto (tras la valoración de su profesional sanitario)',
    ],
    steps: [
      ['Valoración inicial', 'Antes de empezar te preguntamos por tus objetivos, lesiones y nivel de actividad.'],
      ['Calentamiento y respiración', 'Activamos la respiración costal y la musculatura profunda.'],
      ['Bloque principal', 'Ejercicios con progresiones para cada nivel, con y sin material.'],
      ['Estiramiento y relajación', 'Cerramos soltando tensiones para que salgas renovado.'],
    ],
    details: [['Duración', '55 minutos'], ['Formato', 'Grupo reducido'], ['Nivel', 'Todos los niveles']],
    faqs: [
      ['¿Necesito experiencia previa para hacer Pilates?', 'No. Las clases se adaptan a cada alumno y cada ejercicio tiene variantes más sencillas y más exigentes.'],
      ['¿Qué diferencia hay entre Pilates suelo y Pilates máquinas?', 'El Pilates suelo se practica sobre esterilla con pequeño material y el propio peso corporal. Es muy completo para ganar control, fuerza y conciencia corporal.'],
      ['¿Cuántas clases a la semana recomendáis?', 'Con dos sesiones semanales se notan cambios en postura y fuerza en pocas semanas. Una sesión semanal también es beneficiosa para mantener.'],
      ['¿Qué tengo que llevar?', 'Ropa cómoda y calcetines antideslizantes. El resto del material lo ponemos nosotros.'],
    ],
    related: ['hipopresivos-mostoles', 'yoga-mostoles', 'osteopatia-mostoles'],
  },
  {
    slug: 'yoga-mostoles',
    cat: 'clases',
    icon: 'yoga',
    name: 'Yoga',
    title: 'Yoga en Móstoles | Clases de Yoga para todos los niveles | NOVA',
    description: 'Clases de Yoga en Móstoles para principiantes y practicantes. Posturas, respiración y relajación para reducir el estrés y ganar flexibilidad. Reserva tu clase.',
    h1: 'Yoga en Móstoles',
    lead: 'Un espacio para moverte, respirar y bajar el ritmo. Clases de Yoga accesibles para todos los cuerpos y niveles.',
    intro: [
      'El Yoga une movimiento, respiración y atención. Las posturas (asanas) dan fuerza y flexibilidad; la respiración (pranayama) y la relajación ayudan a calmar el sistema nervioso y a gestionar mejor el estrés del día a día.',
      'Nuestras clases combinan secuencias fluidas con posturas mantenidas, siempre con alternativas para que nadie se quede atrás. No hace falta ser flexible: el Yoga sirve precisamente para llegar a serlo.',
    ],
    benefits: [
      'Reduce el estrés y la ansiedad',
      'Mejora la flexibilidad y el equilibrio',
      'Fortalece sin impacto',
      'Favorece un descanso más profundo',
      'Aumenta la conciencia corporal y la concentración',
    ],
    forWho: [
      'Principiantes que quieren empezar con buena base',
      'Personas con estrés, insomnio o mucha carga mental',
      'Quien busca complementar otros deportes con movilidad',
      'Practicantes que quieren profundizar en su práctica',
    ],
    steps: [
      ['Llegada y centrado', 'Unos minutos de respiración para aterrizar en la clase.'],
      ['Movilidad y saludos', 'Calentamos el cuerpo con secuencias suaves.'],
      ['Posturas', 'Trabajo de fuerza, equilibrio y apertura con variantes por nivel.'],
      ['Relajación final', 'Savasana guiada para integrar la práctica.'],
    ],
    details: [['Duración', '60 minutos'], ['Formato', 'Grupo reducido'], ['Nivel', 'Todos los niveles']],
    faqs: [
      ['No soy flexible, ¿puedo hacer Yoga?', 'Sí. La flexibilidad es un resultado de la práctica, no un requisito. Usamos bloques, cinturones y cojines para adaptar las posturas.'],
      ['¿Qué tipo de Yoga hacéis?', 'Una práctica de Hatha Yoga con influencias de Vinyasa: posturas conscientes, respiración y relajación, adaptada al grupo.'],
      ['¿Puedo hacer Yoga si tengo dolor de espalda?', 'En muchos casos sí, y puede ayudar. Cuéntanoslo antes de la clase para adaptar las posturas y, si tienes una lesión, consulta con tu médico.'],
    ],
    related: ['pilates-mostoles', 'taichi-mostoles', 'masajes-mostoles'],
  },
  {
    slug: 'hipopresivos-mostoles',
    cat: 'clases',
    icon: 'breath',
    name: 'Hipopresivos',
    title: 'Hipopresivos en Móstoles | Suelo pélvico, abdomen y postparto | NOVA',
    description: 'Clases de gimnasia abdominal hipopresiva en Móstoles. Tonifica el abdomen, cuida el suelo pélvico y mejora la postura. Ideal en el posparto. Pide información.',
    h1: 'Hipopresivos en Móstoles',
    lead: 'Gimnasia abdominal hipopresiva para tonificar la faja abdominal, cuidar el suelo pélvico y mejorar la postura sin impacto.',
    intro: [
      'Los hipopresivos son una técnica postural y respiratoria que reduce la presión dentro del abdomen. Al hacerlo, la musculatura abdominal profunda y el suelo pélvico se activan de forma refleja, algo que los abdominales tradicionales no consiguen.',
      'Aprender la técnica requiere guía: en grupos muy reducidos te enseñamos paso a paso la respiración, la apnea espiratoria y las posturas, para que puedas integrarla también en tu día a día.',
    ],
    benefits: [
      'Reduce el perímetro de cintura y tonifica el abdomen',
      'Fortalece y protege el suelo pélvico',
      'Ayuda en la recuperación posparto',
      'Mejora la postura y alivia el dolor lumbar',
      'Mejora la capacidad respiratoria',
    ],
    forWho: [
      'Mujeres en posparto, una vez superada la cuarentena y con valoración profesional',
      'Personas con diástasis abdominal o debilidad del suelo pélvico',
      'Deportistas de impacto (running, crossfit) que quieren proteger el suelo pélvico',
      'Cualquier persona que quiera mejorar su postura y su core',
    ],
    steps: [
      ['Aprendizaje de la respiración', 'Respiración costal y apnea espiratoria, la base de la técnica.'],
      ['Posturas', 'Secuencia de posturas de pie, de rodillas, sentados y tumbados.'],
      ['Integración', 'Ejercicios para llevar la técnica a la vida diaria.'],
    ],
    details: [['Duración', '45–55 minutos'], ['Formato', 'Grupo muy reducido o individual'], ['Nivel', 'Iniciación y avanzado']],
    faqs: [
      ['¿Cuándo puedo empezar con hipopresivos después del parto?', 'Habitualmente a partir de las 6–8 semanas, cuando tu matrona, ginecólogo o fisioterapeuta de suelo pélvico lo valore.'],
      ['¿Cuánto tardaré en notar resultados?', 'Con práctica regular (2–3 veces por semana) muchas personas notan cambios en la cintura y la postura en 6–8 semanas.'],
      ['¿Hay contraindicaciones?', 'No se recomiendan durante el embarazo ni en personas con hipertensión no controlada. Consúltanos antes de empezar.'],
    ],
    related: ['pilates-mostoles', 'yoga-mostoles', 'drenaje-linfatico-mostoles'],
  },
  {
    slug: 'entrenamiento-funcional-mostoles',
    cat: 'clases',
    icon: 'circuit',
    name: 'Circuito Funcional',
    title: 'Entrenamiento Funcional en Móstoles | Circuito | NOVA',
    description: 'Circuito de entrenamiento funcional en Móstoles: fuerza, resistencia, coordinación y movilidad en grupos reducidos y adaptado a tu nivel. Reserva tu plaza.',
    h1: 'Entrenamiento funcional en Móstoles',
    lead: 'Un circuito que combina fuerza, resistencia, coordinación y movilidad para trabajar todo el cuerpo de forma equilibrada.',
    intro: [
      'El entrenamiento funcional se basa en movimientos que usamos en la vida real: empujar, tirar, agacharse, girar o cargar peso. Entrenarlos nos hace más fuertes y más resistentes a las lesiones en el día a día.',
      'Nuestro Circuito Funcional se organiza por estaciones con kettlebells, bandas, fitballs, TRX y peso corporal. Cada ejercicio tiene variantes, así que en la misma clase conviven personas que empiezan y personas muy entrenadas.',
    ],
    benefits: [
      'Gana fuerza útil para el día a día',
      'Mejora la resistencia cardiovascular',
      'Quema calorías y mejora la composición corporal',
      'Trabaja coordinación, equilibrio y agilidad',
      'Entrenamientos variados que no aburren',
    ],
    forWho: [
      'Quien quiere ponerse en forma sin ir a un gimnasio masificado',
      'Personas que buscan un entrenamiento completo en menos de una hora',
      'Quien ya hace Pilates o Yoga y quiere sumar fuerza y cardio',
    ],
    steps: [
      ['Calentamiento dinámico', 'Activación articular y muscular.'],
      ['Circuito por estaciones', 'Bloques de trabajo y descanso adaptados a cada nivel.'],
      ['Vuelta a la calma', 'Movilidad y estiramientos para recuperar.'],
    ],
    details: [['Duración', '50 minutos'], ['Formato', 'Grupo reducido'], ['Intensidad', 'Adaptable']],
    faqs: [
      ['¿Es muy intenso?', 'La intensidad la marcas tú. El entrenador adapta cargas, tiempos y ejercicios a cada persona.'],
      ['¿Puedo combinarlo con Pilates?', 'Es una combinación excelente: el funcional aporta fuerza y cardio, y el Pilates control y movilidad.'],
    ],
    related: ['pilates-mostoles', 'hipopresivos-mostoles', 'masajes-mostoles'],
  },
  {
    slug: 'taichi-mostoles',
    cat: 'clases',
    icon: 'taichi',
    name: 'Taichí',
    title: 'Taichí en Móstoles | Clases de Tai Chi para todas las edades | NOVA',
    description: 'Clases de Taichí en Móstoles: movimiento lento, equilibrio y calma mental. Ideal para mayores y para reducir el estrés. Ven a probar una clase.',
    h1: 'Taichí en Móstoles',
    lead: 'Movimiento lento y fluido para mejorar el equilibrio, la coordinación y la calma mental. Una práctica para todas las edades.',
    intro: [
      'El Taichí es un arte tradicional chino que encadena movimientos suaves y continuos con la respiración. A menudo se le llama "meditación en movimiento" por su efecto relajante.',
      'Es una de las actividades más recomendadas para mantener la movilidad, prevenir caídas en personas mayores y reducir el estrés en cualquier etapa de la vida.',
    ],
    benefits: [
      'Mejora el equilibrio y previene caídas',
      'Aumenta la movilidad articular',
      'Reduce el estrés y la tensión',
      'Mejora la coordinación y la memoria',
      'Actividad de bajo impacto apta para casi todos',
    ],
    forWho: [
      'Personas mayores que quieren mantenerse activas',
      'Quien busca una actividad tranquila y meditativa',
      'Personas con articulaciones sensibles',
    ],
    steps: [
      ['Calentamiento suave', 'Movilidad articular y respiración.'],
      ['Aprendizaje de la forma', 'Secuencias de movimientos paso a paso.'],
      ['Práctica y quietud', 'Encadenamos la forma y cerramos con un momento de calma.'],
    ],
    details: [['Duración', '60 minutos'], ['Formato', 'Grupo reducido'], ['Nivel', 'Todas las edades']],
    faqs: [
      ['¿Hay edad para empezar Taichí?', 'No. Es una de las prácticas más accesibles y se adapta a cualquier edad y condición física.'],
      ['¿Necesito ropa especial?', 'Ropa cómoda y calzado plano y flexible.'],
    ],
    related: ['yoga-mostoles', 'pilates-mostoles', 'reflexologia-mostoles'],
  },
  {
    slug: 'clases-online',
    cat: 'clases',
    icon: 'online',
    name: 'Sesiones online',
    title: 'Clases de Pilates y Yoga Online en directo | NOVA Móstoles',
    description: 'Sesiones online de Pilates, Yoga e Hipopresivos con NOVA Centro de Bienestar. Entrena y relájate desde casa con la misma atención que en el centro.',
    h1: 'Sesiones online de Pilates y Yoga',
    lead: 'Entrena y relájate desde casa con la misma atención y cercanía que en el centro.',
    intro: [
      'Si no puedes venir al centro, la clase va a ti. Nuestras sesiones online están pensadas para mejorar tu bienestar físico y mental estés donde estés.',
      'Puedes hacerlas en directo, con correcciones en tiempo real, o como sesiones individuales adaptadas a tus objetivos.',
    ],
    benefits: [
      'Sin desplazamientos: entrena desde casa o de viaje',
      'Correcciones en directo',
      'Horarios flexibles',
      'Solo necesitas una esterilla y algo de espacio',
    ],
    forWho: [
      'Personas con horarios complicados',
      'Quien vive fuera de Móstoles',
      'Alumnos del centro que están de viaje',
    ],
    steps: [
      ['Reserva', 'Escríbenos y te enviamos el enlace de la sesión.'],
      ['Conexión', 'Conéctate desde el móvil, la tablet o el ordenador.'],
      ['Clase', 'Sesión guiada con correcciones en tiempo real.'],
    ],
    details: [['Duración', '45–60 minutos'], ['Formato', 'Grupal o individual'], ['Plataforma', 'Videollamada']],
    faqs: [
      ['¿Qué necesito para las clases online?', 'Una esterilla, ropa cómoda, conexión a internet y un dispositivo con cámara.'],
      ['¿Puedo combinar clases presenciales y online?', 'Sí, muchos alumnos lo hacen para no perder la constancia.'],
    ],
    related: ['pilates-mostoles', 'yoga-mostoles', 'hipopresivos-mostoles'],
  },

  // ───────────── TERAPIAS ─────────────
  {
    slug: 'drenaje-linfatico-mostoles',
    cat: 'terapias',
    icon: 'drop',
    name: 'Drenaje linfático',
    title: 'Drenaje Linfático en Móstoles | Retención y piernas | NOVA',
    description: 'Drenaje linfático manual en Móstoles para reducir la retención de líquidos, la hinchazón y la sensación de piernas cansadas. Pide cita en NOVA.',
    h1: 'Drenaje linfático en Móstoles',
    lead: 'Una técnica manual suave y rítmica que ayuda al cuerpo a eliminar líquidos retenidos y deja una sensación inmediata de ligereza.',
    intro: [
      'El drenaje linfático manual estimula el sistema linfático mediante maniobras lentas, suaves y repetitivas que siguen el recorrido de la linfa. Su objetivo es favorecer la evacuación de líquidos y sustancias de desecho.',
      'Es un tratamiento muy relajante y se utiliza tanto con fines estéticos —retención, celulitis, hinchazón— como para mejorar el bienestar en personas con piernas cansadas o pesadez.',
    ],
    benefits: [
      'Reduce la retención de líquidos y la hinchazón',
      'Alivia la sensación de piernas cansadas',
      'Mejora el aspecto de la piel y la celulitis',
      'Efecto relajante sobre el sistema nervioso',
      'Complementa tratamientos de remodelación corporal',
    ],
    forWho: [
      'Personas con retención de líquidos o pesadez de piernas',
      'Quien pasa muchas horas de pie o sentado',
      'Como complemento a la maderoterapia o a un plan de ejercicio',
    ],
    steps: [
      ['Entrevista', 'Valoramos tu caso y descartamos contraindicaciones.'],
      ['Apertura de ganglios', 'Comenzamos por las zonas ganglionares principales.'],
      ['Drenaje por zonas', 'Maniobras lentas y rítmicas en piernas, abdomen o la zona que lo requiera.'],
      ['Recomendaciones', 'Pautas de hidratación y movimiento para potenciar el efecto.'],
    ],
    details: [['Duración', '50–60 minutos'], ['Formato', 'Sesión individual'], ['Frecuencia', 'Bonos de varias sesiones']],
    faqs: [
      ['¿Cuántas sesiones de drenaje linfático necesito?', 'Depende del objetivo. Para retención y piernas cansadas suele recomendarse un ciclo de 6–10 sesiones, una o dos por semana.'],
      ['¿El drenaje linfático duele?', 'No. Es una técnica muy suave, con poca presión, y la mayoría de personas la encuentra muy relajante.'],
      ['¿Tiene contraindicaciones?', 'No se aplica en caso de infecciones agudas, trombosis, insuficiencia cardiaca descompensada o algunos procesos oncológicos activos sin autorización médica. Te preguntaremos antes de empezar.'],
    ],
    related: ['maderoterapia-mostoles', 'masajes-mostoles', 'reflexologia-mostoles'],
  },
  {
    slug: 'maderoterapia-mostoles',
    cat: 'terapias',
    icon: 'wood',
    name: 'Maderoterapia',
    title: 'Maderoterapia en Móstoles | Masaje reductor y anticelulítico | NOVA',
    description: 'Maderoterapia en Móstoles: masaje con utensilios de madera para moldear la figura, reducir la celulitis y activar la circulación. Reserva tu sesión.',
    h1: 'Maderoterapia en Móstoles',
    lead: 'Masaje con utensilios de madera que activa la circulación, ayuda a moldear la silueta y mejora el aspecto de la celulitis.',
    intro: [
      'La maderoterapia utiliza rodillos, copas y tablas de madera de distintas formas para trabajar el tejido con maniobras de amasamiento, presión y vibración. Estimula la circulación sanguínea y linfática y ayuda a movilizar la grasa localizada.',
      'Combinada con drenaje linfático, hidratación y ejercicio, es una de las técnicas naturales más demandadas para la remodelación corporal.',
    ],
    benefits: [
      'Mejora el aspecto de la piel de naranja',
      'Ayuda a moldear cintura, glúteos y piernas',
      'Activa la circulación y el drenaje',
      'Tonifica y reafirma la piel',
      'Libera tensión muscular',
    ],
    forWho: [
      'Personas que quieren tratar celulitis o grasa localizada',
      'Quien busca un tratamiento corporal natural y sin aparatología',
      'Como complemento de un plan de entrenamiento',
    ],
    steps: [
      ['Valoración', 'Definimos las zonas y el objetivo del tratamiento.'],
      ['Preparación', 'Calentamos el tejido con maniobras manuales.'],
      ['Trabajo con madera', 'Aplicamos los utensilios adecuados a cada zona.'],
      ['Drenaje final', 'Terminamos favoreciendo la eliminación de líquidos.'],
    ],
    details: [['Duración', '50–60 minutos'], ['Formato', 'Sesión individual'], ['Frecuencia', 'Ciclos de 8–10 sesiones']],
    faqs: [
      ['¿La maderoterapia duele?', 'La presión es intensa pero tolerable y se ajusta a cada persona. Las primeras sesiones pueden ser algo más sensibles.'],
      ['¿Cuándo se ven resultados?', 'Normalmente a partir de la 4ª–6ª sesión, especialmente si se acompaña de buena hidratación y actividad física.'],
      ['¿Puedo combinarla con drenaje linfático?', 'Sí, es la combinación ideal: la maderoterapia moviliza y el drenaje ayuda a eliminar.'],
    ],
    related: ['drenaje-linfatico-mostoles', 'masajes-mostoles', 'entrenamiento-funcional-mostoles'],
  },
  {
    slug: 'masajes-mostoles',
    cat: 'terapias',
    icon: 'hands',
    name: 'Masaje holístico',
    title: 'Masajes en Móstoles | Relajante y descontracturante | NOVA',
    description: 'Masajes en Móstoles: masaje holístico, relajante y descontracturante adaptado a ti. Libera tensiones y recupera el equilibrio cuerpo-mente. Pide cita.',
    h1: 'Masajes en Móstoles',
    lead: 'Masaje holístico que trata el cuerpo como un todo: libera tensiones físicas y ayuda a soltar el estrés acumulado.',
    intro: [
      'Un masaje holístico no se limita a una zona: integra técnicas relajantes y descontracturantes, respiración y atención a cómo te sientes para restablecer el equilibrio entre cuerpo y mente.',
      'Cada sesión se adapta a lo que necesitas ese día: más presión para contracturas de cuello y espalda, o maniobras envolventes para desconectar por completo.',
    ],
    benefits: [
      'Alivia contracturas y tensión muscular',
      'Reduce el estrés y mejora el estado de ánimo',
      'Mejora la calidad del sueño',
      'Activa la circulación',
      'Te regala una hora solo para ti',
    ],
    forWho: [
      'Personas con tensión en cuello, hombros y espalda',
      'Quien atraviesa épocas de estrés o cansancio',
      'Como regalo para alguien especial',
    ],
    steps: [
      ['Escucha', 'Hablamos de cómo estás y qué zonas necesitan atención.'],
      ['Masaje', 'Combinamos técnicas según tu necesidad.'],
      ['Integración', 'Unos minutos de calma antes de volver a tu día.'],
    ],
    details: [['Duración', '30, 60 o 90 minutos'], ['Formato', 'Sesión individual'], ['Regalo', 'Pregunta por tarjetas regalo']],
    faqs: [
      ['¿Qué diferencia hay entre masaje relajante y descontracturante?', 'El relajante usa maniobras suaves y envolventes para calmar; el descontracturante trabaja con más presión sobre contracturas concretas. En el holístico los combinamos.'],
      ['¿Puedo regalar un masaje?', 'Escríbenos por WhatsApp y te contamos las opciones para regalar una sesión.'],
    ],
    related: ['drenaje-linfatico-mostoles', 'reflexologia-mostoles', 'terapia-craneosacral-mostoles'],
  },
  {
    slug: 'osteopatia-mostoles',
    cat: 'terapias',
    icon: 'spine',
    name: 'Osteopatía',
    title: 'Osteopatía en Móstoles | Tratamiento manual de espalda y cuello | NOVA',
    description: 'Osteopatía en Móstoles: terapia manual para dolor de espalda, cuello, tensión y movilidad. Valoración global y tratamiento personalizado. Pide cita.',
    h1: 'Osteopatía en Móstoles',
    lead: 'Terapia manual que busca el origen de la molestia y trabaja el cuerpo de forma global para recuperar la movilidad.',
    intro: [
      'La osteopatía entiende el cuerpo como una unidad: una restricción en una zona puede generar molestias en otra. Por eso la valoración es global y el tratamiento combina técnicas articulares, musculares, fasciales y viscerales suaves.',
      'Es una terapia complementaria que puede ayudar con tensiones de espalda y cuello, rigidez, cefaleas tensionales o molestias posturales. No sustituye al diagnóstico ni al tratamiento médico.',
    ],
    benefits: [
      'Ayuda a aliviar molestias de espalda y cuello',
      'Mejora la movilidad articular',
      'Reduce la tensión muscular y fascial',
      'Enfoque global, no solo del síntoma',
    ],
    forWho: [
      'Personas con molestias de espalda, cuello o tensión mandibular',
      'Quien busca un abordaje manual global',
      'Deportistas y personas con trabajos posturales exigentes',
    ],
    steps: [
      ['Historia', 'Repasamos tus antecedentes y la molestia actual.'],
      ['Valoración', 'Exploración de postura y movilidad.'],
      ['Tratamiento', 'Técnicas manuales adaptadas.'],
      ['Pautas', 'Ejercicios y recomendaciones para casa.'],
    ],
    details: [['Duración', '50–60 minutos'], ['Formato', 'Sesión individual'], ['Ropa', 'Cómoda']],
    faqs: [
      ['¿Cuántas sesiones de osteopatía necesitaré?', 'Depende del caso. Tras la primera sesión te daremos una estimación; muchas molestias mejoran en 2–4 sesiones.'],
      ['¿Es lo mismo que fisioterapia?', 'No. Son disciplinas distintas y complementarias. Ante una lesión o dolor intenso, consulta primero con tu médico.'],
    ],
    related: ['terapia-craneosacral-mostoles', 'masajes-mostoles', 'pilates-mostoles'],
  },
  {
    slug: 'reflexologia-mostoles',
    cat: 'terapias',
    icon: 'foot',
    name: 'Reflexología podal',
    title: 'Reflexología Podal en Móstoles | Relajación profunda | NOVA',
    description: 'Reflexología podal en Móstoles: masaje en puntos reflejos de los pies para relajarte en profundidad y mejorar tu bienestar general. Reserva tu sesión.',
    h1: 'Reflexología podal en Móstoles',
    lead: 'Un masaje en los pies que trabaja puntos reflejos para inducir una relajación profunda y equilibrar el cuerpo.',
    intro: [
      'La reflexología podal parte de la idea de que en los pies existen zonas reflejas relacionadas con distintas partes del cuerpo. Mediante presiones específicas se busca estimular el bienestar general.',
      'Más allá de su enfoque tradicional, es una de las terapias más relajantes que existen: perfecta para desconectar, mejorar el descanso y aliviar los pies cansados.',
    ],
    benefits: [
      'Relajación profunda y reducción del estrés',
      'Alivio de pies cansados',
      'Mejora la sensación de descanso',
      'Activa la circulación en piernas y pies',
    ],
    forWho: [
      'Personas con estrés o dificultad para desconectar',
      'Quien pasa muchas horas de pie',
      'Personas que no se sienten cómodas con un masaje corporal completo',
    ],
    steps: [
      ['Baño y preparación', 'Preparamos los pies para la sesión.'],
      ['Reflexología', 'Presiones sobre las zonas reflejas.'],
      ['Cierre', 'Masaje relajante final.'],
    ],
    details: [['Duración', '45–60 minutos'], ['Formato', 'Sesión individual']],
    faqs: [
      ['¿La reflexología duele?', 'Algunos puntos pueden ser sensibles, pero la presión se adapta a ti y la sensación general es muy agradable.'],
      ['¿Sirve para dormir mejor?', 'Muchas personas notan un descanso más profundo tras la sesión gracias a su efecto relajante.'],
    ],
    related: ['masajes-mostoles', 'terapia-craneosacral-mostoles', 'drenaje-linfatico-mostoles'],
  },
  {
    slug: 'terapia-craneosacral-mostoles',
    cat: 'terapias',
    icon: 'head',
    name: 'Terapia sacro-craneal',
    title: 'Terapia Craneosacral en Móstoles | NOVA Bienestar',
    description: 'Terapia sacro-craneal (craneosacral) en Móstoles: técnica manual muy suave para liberar tensiones y calmar el sistema nervioso. Pide cita en NOVA.',
    h1: 'Terapia craneosacral en Móstoles',
    lead: 'Una técnica manual muy suave que trabaja desde el cráneo hasta el sacro para liberar tensiones profundas y calmar el sistema nervioso.',
    intro: [
      'La terapia sacro-craneal utiliza contactos ligeros sobre el cráneo, la columna y el sacro para escuchar y acompañar los ritmos del cuerpo y liberar restricciones en los tejidos.',
      'Es una de las técnicas más suaves que existen y produce un estado de relajación profunda. Se utiliza como apoyo en casos de estrés, tensión cervical o mandibular y dificultad para descansar.',
    ],
    benefits: [
      'Relajación profunda del sistema nervioso',
      'Alivio de tensión cervical y mandibular',
      'Ayuda a gestionar el estrés',
      'Mejora la sensación de descanso',
    ],
    forWho: [
      'Personas con estrés, tensión o bruxismo',
      'Quien busca un tratamiento muy suave y no invasivo',
      'Como complemento a la osteopatía o al masaje',
    ],
    steps: [
      ['Conversación', 'Hablamos de cómo te encuentras.'],
      ['Sesión', 'Tumbado y vestido, con contactos suaves.'],
      ['Integración', 'Tiempo para volver con calma.'],
    ],
    details: [['Duración', '50–60 minutos'], ['Formato', 'Sesión individual'], ['Ropa', 'Vestido y cómodo']],
    faqs: [
      ['¿Qué se siente en una sesión craneosacral?', 'La mayoría de personas siente calor, pesadez y una relajación muy profunda; algunas llegan a dormirse.'],
      ['¿Sustituye a un tratamiento médico?', 'No. Es una terapia complementaria de bienestar.'],
    ],
    related: ['osteopatia-mostoles', 'reflexologia-mostoles', 'masajes-mostoles'],
  },

  // ───────────── ESTÉTICA ─────────────
  {
    slug: 'lifting-pestanas-mostoles',
    cat: 'estetica',
    icon: 'lash',
    name: 'Lifting de pestañas',
    title: 'Lifting de Pestañas en Móstoles | Con tinte, resultado natural | NOVA',
    description: 'Lifting de pestañas en Móstoles: eleva y riza tus pestañas naturales durante 6–8 semanas, con tinte opcional. Sin extensiones ni mantenimiento. Pide cita.',
    h1: 'Lifting de pestañas en Móstoles',
    lead: 'Eleva, riza y define tus pestañas naturales durante semanas, sin extensiones ni rizador.',
    intro: [
      'El lifting de pestañas es un tratamiento profesional que eleva y curva las pestañas desde la raíz utilizando moldes de silicona y productos específicos. El resultado es una mirada más abierta y despierta de forma natural.',
      'Podemos completarlo con tinte para que las pestañas se vean más oscuras y definidas, incluso sin máscara.',
    ],
    benefits: [
      'Mirada más abierta y luminosa',
      'Resultado natural con tus propias pestañas',
      'Dura entre 6 y 8 semanas',
      'Sin mantenimiento diario ni rizador',
      'Opción con tinte para más definición',
    ],
    forWho: [
      'Personas con pestañas rectas o hacia abajo',
      'Quien quiere ahorrar tiempo de maquillaje',
      'Quien prefiere una alternativa natural a las extensiones',
    ],
    steps: [
      ['Limpieza', 'Desmaquillado y preparación de la zona.'],
      ['Moldes', 'Elegimos el molde de silicona según el efecto deseado.'],
      ['Lifting y fijado', 'Aplicamos los productos por fases.'],
      ['Tinte y nutrición', 'Opcional: tinte y sérum nutritivo.'],
    ],
    details: [['Duración', '45–60 minutos'], ['Resultado', '6–8 semanas'], ['Opciones', 'Con o sin tinte']],
    faqs: [
      ['¿Cuánto dura el lifting de pestañas?', 'Entre 6 y 8 semanas, lo que tarda en renovarse el ciclo natural de la pestaña.'],
      ['¿Puedo mojarme las pestañas después?', 'Conviene evitar agua, vapor y maquillaje en las 24 horas posteriores.'],
      ['¿Daña las pestañas?', 'Aplicado por una profesional y con la frecuencia adecuada, no. Terminamos con un sérum nutritivo.'],
    ],
    related: ['microblading-mostoles', 'spa-capilar-mostoles', 'masajes-mostoles'],
  },
  {
    slug: 'microblading-mostoles',
    cat: 'estetica',
    icon: 'brow',
    name: 'Microblading',
    title: 'Microblading en Móstoles | Cejas pelo a pelo naturales | NOVA',
    description: 'Microblading de cejas en Móstoles: técnica pelo a pelo para cejas definidas y naturales, diseñadas según tu rostro. Valoración previa sin compromiso.',
    h1: 'Microblading de cejas en Móstoles',
    lead: 'Cejas definidas y naturales con la técnica pelo a pelo, diseñadas para tu rostro.',
    intro: [
      'El microblading es una técnica de micropigmentación semipermanente que dibuja trazos finos que imitan el vello natural de la ceja. Permite rellenar huecos, corregir la forma o crear una ceja completa.',
      'Todo empieza con un diseño previo medido según las proporciones de tu cara, para que el resultado sea armónico y natural.',
    ],
    benefits: [
      'Cejas definidas las 24 horas',
      'Efecto pelo a pelo muy natural',
      'Corrige asimetrías y rellena huecos',
      'Ahorra tiempo de maquillaje',
    ],
    forWho: [
      'Personas con cejas escasas o despobladas',
      'Quien quiere corregir la forma de sus cejas',
      'Personas que han perdido vello en las cejas',
    ],
    steps: [
      ['Diseño', 'Medimos y dibujamos la ceja ideal para tu rostro.'],
      ['Anestesia tópica', 'Para que el proceso sea cómodo.'],
      ['Microblading', 'Trazado pelo a pelo con pigmento.'],
      ['Retoque', 'Revisión a las 4–6 semanas para perfeccionar.'],
    ],
    details: [['Duración', '2 horas aprox.'], ['Retoque', 'A las 4–6 semanas'], ['Duración del resultado', '12–18 meses']],
    faqs: [
      ['¿Cuánto dura el microblading?', 'Entre 12 y 18 meses, según el tipo de piel y los cuidados.'],
      ['¿Duele?', 'Se aplica anestesia tópica, por lo que la mayoría de personas lo describe como una molestia leve.'],
      ['¿Hay que hacer retoque?', 'Sí, a las 4–6 semanas, para fijar el pigmento y ajustar detalles.'],
    ],
    related: ['lifting-pestanas-mostoles', 'spa-capilar-mostoles', 'terapia-craneosacral-mostoles'],
  },
  {
    slug: 'spa-capilar-mostoles',
    cat: 'estetica',
    icon: 'hair',
    name: 'Spa capilar',
    title: 'Spa Capilar en Móstoles | Head Spa y masaje | NOVA',
    description: 'Spa capilar (head spa) en Móstoles: limpieza profunda, tratamiento del cuero cabelludo y masaje relajante. Ciencia, estética y relax en una experiencia única.',
    h1: 'Spa capilar en Móstoles',
    lead: 'Una experiencia que combina el cuidado del cuero cabelludo con un masaje profundamente relajante.',
    intro: [
      'El spa capilar, también conocido como head spa, es un ritual que cuida la salud del cuero cabelludo —la base de un cabello bonito— mientras te regala un momento de desconexión total.',
      'Incluye análisis, limpieza profunda, exfoliación, tratamiento específico según tus necesidades y un masaje craneal y cervical con agua templada.',
    ],
    benefits: [
      'Limpieza profunda del cuero cabelludo',
      'Cabello más brillante y ligero',
      'Ayuda con caspa, grasa o sequedad',
      'Masaje craneal muy relajante',
      'Alivio de la tensión cervical',
    ],
    forWho: [
      'Personas con cuero cabelludo graso, seco o sensible',
      'Quien busca un ritual de relajación diferente',
      'Una idea de regalo original',
    ],
    steps: [
      ['Diagnóstico', 'Observamos el estado del cuero cabelludo.'],
      ['Limpieza y exfoliación', 'Eliminamos residuos y células muertas.'],
      ['Tratamiento', 'Mascarilla y activos según tu necesidad.'],
      ['Masaje', 'Masaje craneal y cervical con agua templada.'],
    ],
    details: [['Duración', '60–75 minutos'], ['Formato', 'Sesión individual'], ['Regalo', 'Pregunta por tarjetas regalo']],
    faqs: [
      ['¿Cada cuánto se recomienda un spa capilar?', 'Una vez al mes es ideal para mantener el cuero cabelludo sano; en casos concretos se puede hacer un ciclo más seguido.'],
      ['¿Sirve para la caída del cabello?', 'Un cuero cabelludo sano favorece un cabello más fuerte, pero ante caída importante conviene consultar con un dermatólogo.'],
    ],
    related: ['masajes-mostoles', 'lifting-pestanas-mostoles', 'terapia-craneosacral-mostoles'],
  },
];

// URLs antiguas de la web actual → nuevas (para las redirecciones 301).
// Las marcadas con * se han visto indexadas en Google; el resto se deducen del menú actual.
export const legacyRedirects = {
  '/index.html': '/',
  '/circuito.html': '/clases/entrenamiento-funcional-mostoles/', // *
  '/online.html': '/clases/clases-online/', // *
  '/talleres.html': '/talleres/', // *
  '/lifting.html': '/estetica/lifting-pestanas-mostoles/', // *
  '/capilar.html': '/estetica/spa-capilar-mostoles/', // *
  '/aviso.html': '/aviso-legal/', // *
  '/pilates.html': '/clases/pilates-mostoles/',
  '/yoga.html': '/clases/yoga-mostoles/',
  '/hipopresivos.html': '/clases/hipopresivos-mostoles/',
  '/taichi.html': '/clases/taichi-mostoles/',
  '/drenaje.html': '/terapias/drenaje-linfatico-mostoles/',
  '/maderoterapia.html': '/terapias/maderoterapia-mostoles/',
  '/masajes.html': '/terapias/masajes-mostoles/',
  '/osteopatia.html': '/terapias/osteopatia-mostoles/',
  '/reflexologia.html': '/terapias/reflexologia-mostoles/',
  '/sacrocraneal.html': '/terapias/terapia-craneosacral-mostoles/',
  '/microblading.html': '/estetica/microblading-mostoles/',
  '/contacto.html': '/contacto/',
};


